#86a0e97pz update diatheke python examples and add ASR stream with partial
cobaltspeech/examples-python pull request #9
Opened 2023-08-14 14:29 UTC by ppcssn

2023-08-14 14:29 UTC, cobaltjenkins commented
Task linked: [CU-86a0e97pz python client](https://app.clickup.com/t/86a0e97pz)

2023-08-14 18:07 UTC, mkylemartin commented on diatheke/audio_client.py
> +# Copyright (2020 -- present) Cobalt Speech and Language, Inc.
can we put 2023 present? maybe to give the impression that this script isn't 3 years old?

2023-08-14 18:23 UTC, mkylemartin requested changes
looks good to me; just a few minor changes / requests.

2023-08-14 18:23 UTC, mkylemartin commented on diatheke/streams.py
> +    """Deprecated. Use client.read_asr_audio() instead."""
why are we including these if they're deprecated?

2023-08-14 18:23 UTC, mkylemartin commented on diatheke/streams.py
> +            writer.write(data.audio)
same comment as above (why keep if deprecated)

2023-08-14 18:23 UTC, mkylemartin commented on diatheke/streams.py
> +        is_text = False
```suggestion
    # Assume we have a byte reader
    is_text = False
    # assign text reader if it's that
    if isinstance(reader, io.TextIOBase):
        is_text = True
```

Whatever one is the most expected/common should be set and then the if statement can check on the alternative case. 

Mostly a style/readability suggestion/

2023-08-14 18:23 UTC, mkylemartin commented on diatheke/streams.py
> +                    return
```suggestion
                    return None
```
[`return` vs `return None` should be the same but just for sake of readability, i prefer `return None`](https://stackoverflow.com/a/15300733)

2023-08-15 05:53 UTC, ppcssn commented on diatheke/streams.py
> +    """Deprecated. Use client.read_asr_audio() instead."""
Good question. I don't know the answer to this either, but Original file is [here](https://github.com/cobaltspeech/sdk-diatheke/blob/master/grpc/py-diatheke/diatheke/streams.py).

2023-08-15 05:54 UTC, ppcssn commented on diatheke/streams.py
> +            writer.write(data.audio)
probably relate to the reason as `read_ASR_audio`

2023-08-15 06:05 UTC, ppcssn commented on diatheke/streams.py
> +                    return
Good point. It aligns with [PEP8](https://peps.python.org/pep-0008/#programming-recommendations),

> Be consistent in return statements. Either all return statements in a function should return an expression, or none of them should. If any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable):

and we also do it in other typed programming languages, so I guess this make sense.

2023-08-18 05:35 UTC, happyalu approved these changes

2023-08-18 05:35 UTC, happyalu commented on diatheke/audio_client.py
> +        if len(result.partial_result.alternatives) != 0:
will this throw an exception if partial_result is None ?

2023-08-18 06:05 UTC, ppcssn commented on diatheke/audio_client.py
> +        if len(result.partial_result.alternatives) != 0:
no, it won't throw anything, that why I need to check the alternatives length

2023-08-18 06:38 UTC, merged